name: docker_build_push

on: push # events

jobs: # jobs
  docker_build_push_job:
    runs-on: ubuntu-latest # runners
    steps: # steps
      - name: check the code
        uses: actions/checkout@v2 # actions
      - name: login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build und push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: saifullahedu0/fastapi_react_docker:latest
